apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: okeymcokoli/mern-backend:v1  # Update with your actual image name
        ports:
        - containerPort: 5050
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/mydatabase"  # Connecting to MongoDB service
