# services:
#   backend:
#     build: ./mern/backend
#     ports:
#       - "5050:5050" 
#     networks:
#       - mern_network
#     environment:
#       MONGO_URI: mongodb://mongo:27017/mydatabase  
#     depends_on:
#       - mongodb

#   frontend:
#     build: ./mern/frontend
#     ports:
#       - "5173:5173"  
#     networks:
#       - mern_network
#     environment:
#       REACT_APP_API_URL: http://backend:5050 

#   mongodb:
#     image: mongo:latest  
#     ports:
#       - "27017:27017"  
#     networks:
#       - mern_network
#     volumes:
#       - mongo-data:/data/db  

# networks:
#   mern_network:
#     driver: bridge 

# volumes:
#   mongo-data:
#     driver: local  # Persist MongoDB data locally


version: '3.8'

services:
  backend:
    build: ./mern/backend
    image: okeymcokoli/mern-backend:v1  # Tag for backend image
    ports:
      - "5050:5050"
    networks:
      - my_network
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongodb

  frontend:
    build: ./mern/frontend
    image: okeymcokoli/mern-frontend:v1  # Tag for frontend image
    ports:
      - "5173:5173"
    networks:
      - my_network
    environment:
      REACT_APP_API_URL: http://backend:5050

  mongodb:
    image: mongo:latest  # You may still use the official MongoDB image, no need to rebuild it unless you want to customize it
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - mcokoli:/data/db

networks:
  my_network:
    driver: bridge

volumes:
  mcokoli:
    driver: local
