replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  storageClass: "standard"  # Set your storage class, or use a local one
  accessMode: ReadWriteOnce
  size: 1Gi

volumePermissions:
  enabled: true
