apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: okeymcokoli/mern-backend:v1-run-16-run-16  # Update with your actual image name
        ports:
        - containerPort: 5050
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/mydatabase"  # Connecting to MongoDB service
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: ClusterIP
